baseURL: "https://yuanfan.rbind.io/"
languageCode: zh-CN
title: "earfanfan | 袁凡"
theme: "hugo-theme-mini"

# Default content language, support en (English) / zh (Chinese) / nl (Dutch) / fr (French) / es (Spanish), default 'en'
defaultContentLanguage: zh

preserveTaxonomyNames: true
footnotereturnlinkcontents: "↩"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]

# !!! exampleSite only, you may need to delete the line: `themesDir: ../../`

hasCJKLanguage: true
permalinks:
  posts: /posts/:slug/

paginate: 10


# enableGoogleAnalytics: false
# googleAnalytics: your-google-analytics-id
# enableBaiduAnalytics: true
baiduAnalytics: 'c2336cad7e77b97703a3cc5e2e516161'
#disqusShortname: your-disqus-shortname

# Hugo Configure Markup
# More info: https://gohugo.io/getting-started/configuration-markup#
markup:
  highlight:
    guessSyntax: true
    style: emacs
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 1
  # needed to render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
  goldmark:
    renderer:
      unsafe: true

# Social links in footer, support github,twitter,stackoverflow,facebook
social:
  # e.g.
  #github: https://github.com/earfanfan
  #twitter: []
  #stackoverflow: your-github-link
  # facebook: your-facebook-link


# Site parameters
params:
  # Site Author
  author: "袁凡"
  # Author biography
  bio: "一天是永恒的缩影，逆水行舟，不进则退"
  # Site Description, used in HTML meat
  description: "YuanFan's Blog"


  ###########################################
  # Optional Configuration
  ###########################################

  # To enable RSS, you could set `enableRSS: true`, default is `true`
  enableRSS: true
  # To enable comments, you may need to set `disqusShortname`
  enableComments: true
  # To enable comments, you may need to set `googleAnalytics`
  enableGoogleAnalytics: true
  # To enable table of content, you could set `showToc: true`, default is `false`
  showToc: true
  # To hidden powerBy message in the page footer, you could set: `showPowerBy: false`, default is `true`
  showPowerBy: true
  # To enable math typesetting , you could set `math: true`, default is `false`
  math: false
  # To hidden post summary in home page, you could set `hiddenPostSummaryInHomePage: true`, default is `false`
  hiddenPostSummaryInHomePage: false
  # Website copy write, default: '© Copyright 2021 ❤️ {params.author}'
  copyright: '© Copyright 2021-2023 ❤️ [阿木狗主](https://github.com/earfanfan)'
  # Extra links in navigation
  links:
  - name: "苦作舟-R"
    path: "/project/"
  - name: "勤为径-小说"
    path: "/story/"

  # You can put your custom css and js to `static` directory, or use remote css and js files which start with `http://` or `https://`
  customCSS:
    ## e.g.
    # - css/custom.css # local css in `static/css/custom.css`
    # - https://example.com/custom.css # remote css
  customJS:
    ## e.g.
    # - js/custom.js # local js in `static/js/custom.js`
    # - https://example.com/custom.js # remote js
